### ISSUE TITLE
使用这个数据集在yolox上map很低的问题

### ISSUE THREAD

**Issue by fanfanfan111** [NicholasCG/GLARE_Dataset#1]
作者你好 我训练出了这个数据集论文中提出的在yolov5上的基线 但是在yolox上 map仅为53 是否是数据集标签的问题？
<img width="485" alt="image" src="https://user-images.githubusercontent.com/104192127/197125352-42d79adb-af53-48aa-9b54-6b14ec1980f9.png">

**Comment by ACAMPUS** [comment]
Hi, very nice work. But I'm also having trouble reproducing it, so I'd appreciate it if you could provide the source code!thanks.

**Comment by NicholasCG** [comment]
Apologies for not seeing this sooner. I will take a look at this when I have the chance.

**Comment by NicholasCG** [comment]
Just to update, I'm going to be checking on this soon (within the next 2 weeks). Apologies for not getting back sooner.

**Comment by NicholasCG** [comment]
Update: Revision has been submitted with new benchmarks, including for YOLOX. The new models and logs will be uploaded soon. Closing.

**Comment by NicholasCG** [comment]
close
